import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Tailwind CSS Workshops</h1>

        <section>
          <Image
            src="https://res.cloudinary.com/practicaldev/image/fetch/s--nMhGDRhf--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://pbs.twimg.com/media/Et0wI8eXYAY1-Jn.jpg"
            alt=""
            width={400}
            height={400}
          />
        </section>

        <div className={styles.grid}>
          <a
            href="https://tailwindcss.com/docs/installation"
            className={styles.card}
          >
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about TailwindCSS features and API.</p>
          </a>

          <a
            href="https://greatminds.atlassian.net/wiki/spaces/DP/pages/2509307939/Responsiveness"
            className={styles.card}
          >
            <h2>Responsiveness Initiative &rarr;</h2>
            <p>Learn about Responsiveness Initiative and Quick Links Ref</p>
          </a>

          <a
            href="https://github.com/greatmindsorg/dp-atomic-ui-lib/pull/1555"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover some components already using TailwindCSS.</p>
          </a>

          <a
            href="https://greatminds.atlassian.net/wiki/spaces/DP/pages/2558558290/TailwindCSS+Workshops"
            className={styles.card}
          >
            <h2>Workshops Calendar &rarr;</h2>
            <p>
              Watch previous sessions and get notified about incoming workshops
            </p>
          </a>
        </div>
      </main>
    </div>
  );
}

export default Home
